"""Build content/geo/earth.png: the ship's world map, an equirectangular
raster of the real Earth's land at 0.125 deg per pixel (2880 x 1440).

    py -3.11 betatest/tools/earth_map.py            (network once; cached geojson)

Source: Natural Earth 1:110m "land" polygons (public domain, no attribution
required; credited anyway in content/geo/earth.json). Fetched from the
nvkelso/natural-earth-vector GitHub mirror and cached beside the output as
content/geo/ne_110m_land.geojson so the raster is reproducible offline.

The picture is deliberately retro: two greens for land, a dark sea, a one-pixel
shore. Pixel (x, y) is lon = x/8 - 180, lat = 90 - y/8; the ship module does
the same arithmetic. Owner, log 20260914-01: "the world map literally needs to
be a map of the whole world ... to scale".
"""
import json
import sys
import urllib.request
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

HERE = Path(__file__).resolve().parent.parent
GEO = HERE / "content" / "geo"
CACHE = GEO / "ne_110m_land.geojson"
OUT = GEO / "earth.png"
META = GEO / "earth.json"
URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
PX_PER_DEG = 8
W, H = 360 * PX_PER_DEG, 180 * PX_PER_DEG

SEA = (14, 32, 56)
LAND = (62, 112, 66)
LAND2 = (56, 102, 60)
SHORE = (128, 150, 110)


def fetch():
    if CACHE.exists():
        return json.loads(CACHE.read_text(encoding="utf-8"))
    req = urllib.request.Request(URL, headers={"User-Agent": "CadenzaArthouse-betatest/1.0"})
    data = urllib.request.urlopen(req, timeout=60).read()
    CACHE.write_bytes(data)
    return json.loads(data.decode("utf-8"))


def px(lon, lat):
    return ((lon + 180) * PX_PER_DEG, (90 - lat) * PX_PER_DEG)


def main():
    gj = fetch()
    img = Image.new("RGB", (W, H), SEA)
    d = ImageDraw.Draw(img)
    rings = 0
    for f in gj["features"]:
        g = f["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        for poly in polys:
            for i, ring in enumerate(poly):
                pts = [px(lon, lat) for lon, lat in ring]
                d.polygon(pts, fill=LAND if i == 0 else SEA)
                rings += 1
    # a subtle checker on land so movement reads on a plain expanse
    pix = img.load()
    for y in range(0, H, 2):
        for x in range(0, W, 2):
            if pix[x, y] == LAND and ((x // 2 + y // 2) % 2 == 0):
                pix[x, y] = LAND2
    # one-pixel shoreline: land pixels with a sea neighbour
    mask = Image.new("L", (W, H), 0)
    mp = mask.load()
    for y in range(H):
        for x in range(W):
            if pix[x, y] != SEA:
                mp[x, y] = 255
    edge = mask.filter(ImageFilter.MinFilter(3))
    ep = edge.load()
    for y in range(H):
        for x in range(W):
            if mp[x, y] and not ep[x, y]:
                pix[x, y] = SHORE
    img.save(OUT, optimize=True)
    META.write_text(json.dumps({
        "_readme": "GENERATED by betatest/tools/earth_map.py. Equirectangular: lon = x/px_per_deg - 180, lat = 90 - y/px_per_deg.",
        "source": "Natural Earth 1:110m land (public domain), via github.com/nvkelso/natural-earth-vector",
        "px_per_deg": PX_PER_DEG, "width": W, "height": H,
    }, indent=2), encoding="utf-8")
    print(f"wrote {OUT} {W}x{H}, {rings} rings; {OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    sys.exit(main())
