<#
.SYNOPSIS
  Compiles ticker items from archive markdown files into news/ticker.json.

.DESCRIPTION
  Scans a source folder (recursively) for .md files and turns their lines into
  ticker items. Two ways a line gets a date:

    1. The file name starts with a date:  2026-07-10-updates.md
       -> every content line in the file uses that date.
    2. The line itself starts with a date:  2026-07-10: text here
       (also accepts "2026-07-10 - text", "2026-07-10 | text", or an em/en dash)
       -> that date wins over the file-name date.

  Lines that are blank, headings (#...), or have no resolvable date are skipped.
  Leading "-" / "*" bullet markers are stripped. A line that is a single
  markdown link, like:
    - 2026-07-10: [New feature: 713 Day](https://cadenzaarthouse.com/0005/)
  becomes a linked ticker item.

  Output: ticker.json next to this script (newest first, top $MaxItems).

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File compile-ticker.ps1 -SourceDir "D:\CadenzaArchive\ticker"

.EXAMPLE
  # For Task Scheduler: compile AND publish to the live site
  powershell -ExecutionPolicy Bypass -File compile-ticker.ps1 -SourceDir "D:\CadenzaArchive\ticker" -CommitPush

.NOTES
  The live site only updates when ticker.json is committed and pushed (GitHub
  Pages serves the repo, not your disk). Use -CommitPush for scheduled runs.
#>
param(
  [Parameter(Mandatory = $true)]
  [string]$SourceDir,

  [string]$OutFile = (Join-Path $PSScriptRoot 'ticker.json'),

  [int]$MaxItems = 12,

  [switch]$CommitPush
)

if (-not (Test-Path $SourceDir)) {
  Write-Error "Source folder not found: $SourceDir"
  exit 1
}

$items = New-Object System.Collections.Generic.List[object]

Get-ChildItem -Path $SourceDir -Filter *.md -File -Recurse | ForEach-Object {
  $fileDate = $null
  if ($_.BaseName -match '^(\d{4}-\d{2}-\d{2})') { $fileDate = $Matches[1] }

  foreach ($line in Get-Content $_.FullName -Encoding UTF8) {
    $t = $line.Trim()
    if (-not $t -or $t.StartsWith('#')) { continue }

    # strip bullet marker
    $t = $t -replace '^[-*]\s+', ''

    # per-line date prefix beats the file-name date (: | - or en/em dash,
    # written as \u escapes so the file stays pure ASCII for PS 5.1)
    $date = $fileDate
    if ($t -match '^(\d{4}-\d{2}-\d{2})\s*[:|\-–—]\s*(.+)$') {
      $date = $Matches[1]
      $t    = $Matches[2].Trim()
    }
    if (-not $date) { continue }

    # whole-line markdown link -> linked item
    $link = $null
    if ($t -match '^\[(.+)\]\((\S+)\)$') {
      $t    = $Matches[1]
      $link = $Matches[2]
    }

    $entry = [ordered]@{ date = $date; text = $t }
    if ($link) { $entry.link = $link }
    $items.Add([pscustomobject]$entry)
  }
}

if ($items.Count -eq 0) {
  Write-Warning "No dated ticker lines found in $SourceDir - ticker.json left unchanged."
  exit 0
}

$selected = $items | Sort-Object date -Descending | Select-Object -First $MaxItems

$payload = [ordered]@{
  _readme    = 'Generated by compile-ticker.ps1 - edit the archive markdown, not this file.'
  _generated = (Get-Date).ToString('yyyy-MM-dd HH:mm')
  items      = @($selected)
}

$payload | ConvertTo-Json -Depth 4 | Out-File -FilePath $OutFile -Encoding utf8
Write-Output "Wrote $($selected.Count) ticker item(s) to $OutFile"

if ($CommitPush) {
  $repo = Split-Path $PSScriptRoot -Parent
  git -C $repo add $OutFile
  $status = git -C $repo status --porcelain -- $OutFile
  if ($status) {
    git -C $repo commit -m "ticker: auto-update $((Get-Date).ToString('yyyy-MM-dd HH:mm'))"
    git -C $repo push
    Write-Output 'Committed and pushed ticker.json.'
  } else {
    Write-Output 'Ticker unchanged - nothing to commit.'
  }
}
