// AUDIO MANAGER
// One interface for all sound: looping music, ambient layers, one-shot SFX, and
// procedural chiptune stingers. Driven by engine events — areas and quests declare
// their audio in JSON data, never in code. Swap an .ogg for a synth track later
// without touching game logic.
//
// Zero dependencies. Music/SFX use HTMLAudioElement; stingers use the built-in
// WebAudio API (no Tone.js — keeps the no-build, no-npm stack intact).
//
// File conventions (referenced by ID from JSON data):
//   music   id -> assets/audio/music/<id>.ogg
//   ambient id -> assets/audio/ambient/<id>.ogg
//   sfx     id -> assets/audio/sfx/<id>.wav
// Missing files are logged once and skipped — audio never crashes the game.

class AudioManager {
  constructor(bus) {
    this.bus = bus;
    this.base = 'assets/audio/';
    this.ctx = null;              // WebAudio context (created on first user gesture)
    this.muted = false;
    this.musicVolume = 0.45;
    this.ambientVolume = 0.35;
    this.sfxVolume = 0.7;

    this.current = null;          // { id, el } currently playing music
    this.ambient = new Map();     // id -> HTMLAudioElement
    this.sfxCache = new Map();    // id -> HTMLAudioElement (template)
    this.missing = new Set();     // ids already reported missing (log once)
    this._fades = new Map();      // el -> interval id

    // Procedural stinger note tables (frequencies in Hz)
    this.NOTE = {
      C4: 261.63, E4: 329.63, G4: 392.0,
      C5: 523.25, E5: 659.25, G5: 783.99, A5: 880.0, C6: 1046.5,
    };
  }

  // Subscribe to the engine's event bus. Audio is purely reactive — it never
  // knows about specific records or quests, only the events they emit.
  wire() {
    this.bus.on('LocationChanged', d => this._onLocation(d));
    this.bus.on('RecordRecovered', () => this.stinger('recover'));
    this.bus.on('ArchiveSynchronized', () => this.stinger('sync'));
  }

  // Must be called from a user gesture (the boot ENTER) or browsers block audio.
  unlock() {
    if (!this.ctx) {
      const AC = window.AudioContext || window.webkitAudioContext;
      if (AC) { try { this.ctx = new AC(); } catch (e) { this.ctx = null; } }
    }
    if (this.ctx && this.ctx.state === 'suspended') this.ctx.resume();
  }

  setMuted(m) {
    this.muted = m;
    const v = m ? 0 : this.musicVolume;
    if (this.current) this.current.el.volume = v;
    for (const el of this.ambient.values()) el.volume = m ? 0 : this.ambientVolume;
  }
  toggleMute() { this.setMuted(!this.muted); return this.muted; }

  _onLocation(data) {
    const loc = data.location || {};
    this.playMusic(loc.music || null);
    // support both `ambient: [..]` and a single `ambience: ".."`
    const amb = loc.ambient || (loc.ambience ? [loc.ambience] : []);
    this.setAmbient(amb);
  }

  // ── Music: crossfade to a new looping track (null = fade to silence) ──
  playMusic(id) {
    if (this.current && this.current.id === id) return;
    const old = this.current;
    if (old) this._fadeOut(old.el, 700, true);
    this.current = null;
    if (!id) return;

    const el = this._makeAudio(`music/${id}.ogg`, id);
    if (!el) return;
    el.loop = true;
    el.volume = 0;
    this.current = { id, el };
    this._play(el);
    if (!this.muted) this._fadeTo(el, this.musicVolume, 700);
  }

  // ── Ambient: a set of looping layers (birds, wind, etc.) ──
  setAmbient(ids) {
    const want = new Set(ids);
    // stop layers no longer wanted
    for (const [id, el] of this.ambient) {
      if (!want.has(id)) { this._fadeOut(el, 600, true); this.ambient.delete(id); }
    }
    // start new layers
    for (const id of want) {
      if (this.ambient.has(id)) continue;
      const el = this._makeAudio(`ambient/${id}.ogg`, id);
      if (!el) continue;
      el.loop = true;
      el.volume = 0;
      this.ambient.set(id, el);
      this._play(el);
      if (!this.muted) this._fadeTo(el, this.ambientVolume, 800);
    }
  }

  // ── One-shot sound effect ──
  playSFX(id) {
    if (this.muted) return;
    const tmpl = this.sfxCache.get(id) || this._makeAudio(`sfx/${id}.wav`, id);
    if (!tmpl) return;
    this.sfxCache.set(id, tmpl);
    const shot = tmpl.cloneNode();    // clone so rapid SFX can overlap
    shot.volume = this.sfxVolume;
    this._play(shot);
  }

  // ── Procedural chiptune stinger — no audio file needed ──
  // A short arpeggio synthesized live. This is the "feels magical, tiny download"
  // path: discovering a record plays a rising motif generated by oscillators.
  stinger(name) {
    if (this.muted) return;
    this.unlock();
    if (!this.ctx) return;

    const seqs = {
      recover: { notes: ['C5', 'E5', 'G5', 'C6'], dur: 0.10, type: 'square', gain: 0.18 },
      sync:    { notes: ['C4', 'G4', 'C5', 'E5', 'G5'], dur: 0.13, type: 'triangle', gain: 0.20 },
      ui:      { notes: ['G5'], dur: 0.05, type: 'square', gain: 0.10 },
    };
    const seq = seqs[name] || seqs.ui;
    const t0 = this.ctx.currentTime;

    seq.notes.forEach((n, i) => {
      const f = this.NOTE[n];
      if (!f) return;
      const osc = this.ctx.createOscillator();
      const g = this.ctx.createGain();
      osc.type = seq.type;
      osc.frequency.value = f;
      const start = t0 + i * seq.dur;
      const end = start + seq.dur;
      // quick attack + decay envelope for a plucky chiptune feel
      g.gain.setValueAtTime(0.0001, start);
      g.gain.exponentialRampToValueAtTime(seq.gain, start + 0.01);
      g.gain.exponentialRampToValueAtTime(0.0001, end);
      osc.connect(g).connect(this.ctx.destination);
      osc.start(start);
      osc.stop(end + 0.02);
    });
  }

  // ── internals ──

  _makeAudio(relPath, id) {
    const url = this.base + relPath;
    const el = new Audio();
    el.addEventListener('error', () => {
      if (!this.missing.has(id)) {
        this.missing.add(id);
        console.info(`[audio] missing (skipped): ${url}`);
      }
    }, { once: true });
    el.src = url;
    return el;
  }

  _play(el) {
    const p = el.play();
    if (p && p.catch) p.catch(() => {}); // ignore autoplay/abort rejections
  }

  _fadeTo(el, target, ms) {
    this._clearFade(el);
    const steps = 20, stepMs = ms / steps;
    const from = el.volume, delta = (target - from) / steps;
    let i = 0;
    const iv = setInterval(() => {
      i++;
      el.volume = Math.max(0, Math.min(1, from + delta * i));
      if (i >= steps) this._clearFade(el);
    }, stepMs);
    this._fades.set(el, iv);
  }

  _fadeOut(el, ms, stopAfter) {
    this._clearFade(el);
    const steps = 20, stepMs = ms / steps;
    const from = el.volume, delta = from / steps;
    let i = 0;
    const iv = setInterval(() => {
      i++;
      el.volume = Math.max(0, from - delta * i);
      if (i >= steps) {
        this._clearFade(el);
        if (stopAfter) { try { el.pause(); el.currentTime = 0; } catch (e) {} }
      }
    }, stepMs);
    this._fades.set(el, iv);
  }

  _clearFade(el) {
    const iv = this._fades.get(el);
    if (iv) { clearInterval(iv); this._fades.delete(el); }
  }
}
